# Generated by Django 5.1.4 on 2024-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="airport",
            name="closest_big_city",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="airport",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="crew",
            name="first_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="crew",
            name="last_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
