# Generated by Django 5.1.4 on 2024-12-18 13:49

import airport.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_airplane_created_at_airplane_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.utils.airplane_image_file_path
            ),
        ),
    ]
