# Generated by Django 5.1.4 on 2024-12-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_alter_airplane_name_alter_airplanetype_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="arrival_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.PositiveSmallIntegerField(
                db_index=True, help_text="Distance in kilometers."
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="row",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
