# Generated by Django 5.1.4 on 2024-12-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_airplane_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="number",
        ),
    ]
